name: Security Prompt Evaluation

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - '**/*prompt*.md'
      - '**/*prompt*.txt'
      - 'prompts/**'

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  evaluate-security-prompts:
    uses: whichguy/prompt-expert-bank/.github/workflows/evaluate-prompts.yml@main
    with:
      pr-number: ${{ github.event.pull_request.number }}
      repository: ${{ github.repository }}
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      anthropic-api-key: ${{ secrets.ANTHROPIC_API_KEY }}